# Generated by viewer template v0.1.0 — DSL-B compatible
set language archimate
set title "VideopacHorse_Web — v0.5.1-Kerstens"
set subtitle "Elk element is herleidbaar naar een bestand, endpoint of gedocumenteerde flow (zie ARCHITECTURE.md / DEPENDENCIES.md / PRINCIPLES.md)"

Driver d_samen "Samen spelen op een G7000"
Driver d_rom "Geen ROM-distributie"
Goal g_scherp "Gast: eigen scherp beeld en geluid"
Principle p1 "P-1 Geen backend voor de emulatie"
Principle p2 "P-2 Site host geen ROM-bytes"
Principle p4 "P-4 Een bestand, een gedrag"
Principle p5 "P-5 Alles via de lockstep"
Requirement req_det "Bit-identieke emulatie aan beide kanten"
BusinessActor a_host "Host"
BusinessActor a_gast "Gast"
BusinessActor a_tel "Telefoon-speler"
BusinessProcess bp_start "Sessie starten (3 codes)"
BusinessProcess bp_join "Meedoen als gast"
BusinessProcess bp_koppel "Joystick koppelen"
BusinessService bs_netplay "Netplay (/videopac/)"
BusinessService bs_stream "Streamversie, gearchiveerd (/videopac/stream/)"
ApplicationComponent ac_index "web/index.html — netplay-pagina"
ApplicationComponent ac_app "web/app.js — glue, invoer, GAMES, config"
ApplicationComponent ac_netplay "web/netplay.js — lockstep"
ApplicationComponent ac_stream "web/stream/ — archief + pairplay.js"
ApplicationComponent ac_redirect "web/2/index.html — doorverwijzing"
ApplicationComponent ac_api "web/api/index.php — pairing en signaling"
ApplicationService as_pair "pair-create / pair-join / pair-end"
ApplicationService as_rtc "rtc-signal-send / -poll"
ApplicationService as_ctrl "ctrl-join / -input / -poll / -leave"
DataObject do_db "pairing.db — sessions, controllers, rtc_signals"
DataObject do_idb "IndexedDB — BIOS en ROM-cache"
DataObject do_games "web/games.json — 65 titels met CRC"
DataObject do_style "web/style.css — gedeelde tokens"
Node n_hc55 "HorseCloud55 — nginx + php8.3-fpm"
Device n_browser_h "Browser host"
Device n_browser_g "Browser gast"
Device n_phone "Android-telefoon"
Artifact ar_wasm "web/g7000.wasm — Core 0.5.1-Kerstens"
Artifact ar_apk "VPHJoystick-v0.5.1 (HorseAPK)"
Artifact ar_dbfile "/var/lib/videopac/pairing.db"
TechnologyService ts_stun "STUN (Google) — geen TURN"
TechnologyService ts_archive "archive.org /cors/ — ROM-bron"
TechnologyService ts_p2p "WebRTC DataChannels: ctl + in"

d_samen -> g_scherp "drijft aan"
d_rom -> p2 "leidt tot"
g_scherp -> req_det "vereist"
req_det -> p5 "stelt eis"
d_samen -> p1 "kadert"
p4 -> ac_app "stuurt"
p5 -> ac_netplay "stuurt"
p2 -> do_games "stuurt"
a_host -> bp_start "voert uit"
a_gast -> bp_join "voert uit"
a_tel -> bp_koppel "voert uit"
bp_start -> bs_netplay "realiseert"
bp_join -> bs_netplay "realiseert"
bp_koppel -> bs_netplay "ondersteunt"
bs_stream -> a_gast "bedient (gearchiveerd)"
ac_index -> ac_app "laadt"
ac_index -> ac_netplay "laadt"
ac_stream -> ac_app "laadt via VPH_BASE"
ac_redirect -> ac_index "verwijst naar"
ac_app -> do_idb "schrijft"
ac_app -> do_games "leest"
ac_index -> do_style "gebruikt"
ac_stream -> do_style "gebruikt"
ac_api -> as_pair "realiseert"
ac_api -> as_rtc "realiseert"
ac_api -> as_ctrl "realiseert"
ac_api -> do_db "schrijft"
ac_netplay -> as_pair "roept aan"
ac_netplay -> as_rtc "roept aan"
ac_app -> as_ctrl "pollt (host)"
ac_netplay -> ts_p2p "gebruikt"
ac_app -> ar_wasm "laadt"
n_hc55 -> ac_api "draait"
n_browser_h -> ac_index "draait"
n_browser_g -> ac_index "draait"
n_phone -> ar_apk "draait"
ar_apk -> as_ctrl "roept aan"
n_hc55 -> ar_dbfile "host"
ts_p2p -> ts_stun "onderhandelt via"
ac_app -> ts_archive "haalt ROM (client-side)"
n_browser_h -> ts_p2p "verbindt"
n_browser_g -> ts_p2p "verbindt"

Viewpoint conceptueel "Conceptueel" {
  -description "Waarom dit bestaat: drijfveren, doel en de principes uit docs/PRINCIPLES.md."
}
Viewpoint logisch "Logisch" {
  -description "Wie doet wat, en welke bestanden dat realiseren. Business + Application."
}
Viewpoint fysiek "Fysiek" {
  -description "Waarop het draait: HC55, twee browsers, telefoon, wasm en de externe bronnen."
}
Viewpoint transacties "Transacties" {
  -description "Twee ketens uit ARCHITECTURE.md: netplay opzetten en telefoon-joystick."
  -attr scenario_default = "netplay_opzetten"
}
Viewpoint journeys "Journeys" {
  -description "De weg van host en gast door de schermen, zoals in docs/screens/README.md."
  -attr scenario_default = "journey_samen_spelen"
}

pos d_samen 140, 80
pos d_rom 420, 80
pos g_scherp 700, 80
pos p1 140, 200
pos p2 420, 200
pos p4 700, 200
pos p5 980, 200
pos req_det 980, 80
pos a_host 140, 340
pos a_gast 140, 430
pos a_tel 140, 520
pos bp_start 380, 340
pos bp_join 380, 430
pos bp_koppel 380, 520
pos bs_netplay 640, 385
pos bs_stream 640, 520
pos ac_index 140, 660
pos ac_app 420, 660
pos ac_netplay 700, 660
pos ac_stream 140, 760
pos ac_redirect 140, 850
pos ac_api 980, 660
pos as_pair 1240, 600
pos as_rtc 1240, 690
pos as_ctrl 1240, 780
pos do_db 980, 780
pos do_idb 420, 780
pos do_games 420, 870
pos do_style 700, 760
pos n_hc55 980, 980
pos n_browser_h 140, 980
pos n_browser_g 420, 980
pos n_phone 700, 980
pos ar_wasm 140, 1080
pos ar_apk 700, 1080
pos ar_dbfile 980, 1080
pos ts_stun 420, 1080
pos ts_archive 1240, 980
pos ts_p2p 280, 1180